### ISSUE TITLE
SPDRM

### ISSUE THREAD

**Issue by Infervip** [tonkeeper/ton-assets#2591]
```yaml
name: SPIDER MASK
description: Meme token by promoting which we will create a sewing production and give every child on the planet new toys.
image: https://avatars.githubusercontent.com/u/199994982?s=400&u=26d98d2eb8e4eaa504fbb5b464f1f738cec97717&v=4
address: EQCptIc_a5c-lNtoiSL1K58O2pZ5GBqjmlDy560pVGeAjNFU 
symbol: SPDRM
websites:
  - "https://x.com/_SP1DERMASK_?t=4kOglJ1S7cEGubXMxqEEZA&s=09"
social:
  - "https://www.instagram.com/sp1dermask?igsh=ZHY2OXg0czgzMnNo"
  ```
