### ISSUE TITLE
SMART COIN

### ISSUE THREAD

**Issue by Infervip** [tonkeeper/ton-assets#2600]
```yaml
name: SMART COIN
description: The coin will be converted into $365 in the "SMARTER" application
The campaign guarantees a buyout at a price of $365
image: https://avatars.githubusercontent.com/u/166627936?s=400&u=eb7324d75dbf6dc5036d4913cc10f5ca2baecf46&v=4
address: EQACqHjZVa9PjieZuBp832hmfmYoVzr6Z4tFqemKR7t9wRjF 
symbol: SMART
websites:
  - "https://www.progress-club.com"
social:
  - "https://www.facebook.com/groups/inferviptoken"
  ```
